import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const compile=source=>`data:text/javascript;base64,${Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}`;
const {emailAddress,emailConfiguration,emailCodeHash,emailUnsubscribeToken,validEmailUnsubscribeToken,sendEmail}=await import(compile(fs.readFileSync('lib/email-protocol.ts','utf8')));
for(const value of ['bad','a@localhost','a\r\nb@example.test','a..b@example.test','.a@example.test','a.@example.test','a@-example.test','a@evil.test\nBcc: other@example.test'])assert.equal(emailAddress(value),null,value);
assert.equal(emailAddress('Name+tag@EXAMPLE.TEST'),'Name+tag@example.test');
const environment={RESEND_API_KEY:'test-key',EMAIL_FROM:'sender@example.test',EMAIL_TOKEN_SECRET:'test-email-secret-'.repeat(3),APP_ORIGIN:'https://app.example.test'};
const configuration=emailConfiguration(environment);assert.ok(configuration);
assert.equal(emailConfiguration({...environment,APP_ORIGIN:'http://app.example.test'}),null);assert.equal(emailConfiguration({...environment,EMAIL_TOKEN_SECRET:'short'}),null);
const code=emailCodeHash(configuration.tokenSecret,'challenge','a@example.test','123456');assert.equal(code.length,64);assert.notEqual(code,emailCodeHash(configuration.tokenSecret,'challenge','b@example.test','123456'));
const token=emailUnsubscribeToken(configuration.tokenSecret,'user','a@example.test',1);assert.equal(validEmailUnsubscribeToken(token,token),true);assert.equal(validEmailUnsubscribeToken('bad',token),false);assert.equal(validEmailUnsubscribeToken(token,emailUnsubscribeToken(configuration.tokenSecret,'user','a@example.test',2)),false);
let captured;
assert.equal(await sendEmail(configuration,{to:'recipient@example.test',subject:'موضوع',text:'متن',unsubscribeUrl:'https://app.example.test/unsubscribe'},'delivery:1',async(url,request)=>{captured={url,request};return Response.json({id:'provider-1'});}), 'provider-1');
assert.equal(captured.url,'https://api.resend.com/emails');assert.equal(captured.request.redirect,'error');assert.equal(captured.request.headers['Idempotency-Key'],'delivery:1');assert.equal(JSON.parse(captured.request.body).headers['List-Unsubscribe-Post'],'List-Unsubscribe=One-Click');
await assert.rejects(()=>sendEmail(configuration,{to:'recipient@example.test',subject:'موضوع',text:'متن'},'delivery:1',async()=>Response.json({error:'private provider details'},{status:429})),/Email delivery rejected/);
await assert.rejects(()=>sendEmail(configuration,{to:'recipient@example.test',subject:'موضوع',text:'متن'},'delivery:1',async()=>Response.json({})),/Email delivery unconfirmed/);
const {notificationAudienceCondition}=await import(compile(fs.readFileSync('lib/notification-queries.ts','utf8')));
const queriesSource=fs.readFileSync('lib/email-notifications.ts','utf8').replace(/^import .*;$/gm,'');
const {newsletterSql,eligibleEmailSql,claimEmailSql}=await import(compile(`const notificationAudienceCondition=${JSON.stringify(notificationAudienceCondition)};\n`+queriesSource));
const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON');for(const {tag} of JSON.parse(fs.readFileSync('drizzle/meta/_journal.json')).entries)db.exec(fs.readFileSync(`drizzle/${tag}.sql`,'utf8'));
const now=Date.now();const sql=(query,values)=>db.prepare(query).all(Object.fromEntries([...new Set(query.match(/\?\d+/g))].map(key=>[key,values[Number(key.slice(1))-1]])));
db.prepare("INSERT INTO users VALUES('user','09121111111','User',?)").run(now);
db.prepare("INSERT INTO user_profiles(user_id,city,interests,notification_preferences,updated_at) VALUES('user','Tehran','[\"art\"]',?,?)").run(JSON.stringify({email:true,newsletter:true}),now);
db.prepare("INSERT INTO account_emails VALUES('user','recipient@example.test',?,?)").run(now-1000,now-1000);
function event(id,{city='Tehran',category='art',sample=0,published=1}={}){db.prepare("INSERT INTO events(id,host_id,title,description,category,venue,address,city,starts_at,ends_at,registration_ends_at,price,sample,published) VALUES(?,'host',?,'Description',?,'Venue','Address',?,?,?, ?,0,?,?)").run(id,id,category,city,now+3600000,now+7200000,now+1800000,sample,published);}
event('art-event');event('private',{published:0});event('sample',{sample:1});event('other-city',{city:'Tabriz'});event('other-topic',{category:'music'});
sql(newsletterSql,[now,'Newsletter','week']);sql(newsletterSql,[now,'Newsletter','week']);
const newsletter=db.prepare("SELECT * FROM notifications").all();assert.equal(newsletter.length,1);assert.equal(newsletter[0].message,'art-event','Newsletter uses only actual public matching city/interests events');
assert.equal(sql(eligibleEmailSql,[now]).length,1);db.prepare("UPDATE events SET published=0 WHERE id='art-event'").run();assert.equal(sql(eligibleEmailSql,[now]).length,0,'Unpublished events withdraw a queued newsletter');db.prepare("UPDATE events SET published=1 WHERE id='art-event'").run();assert.equal(sql(claimEmailSql,[newsletter[0].id,'recipient@example.test',now-1000,now])[0].attempts,1);assert.equal(sql(claimEmailSql,[newsletter[0].id,'recipient@example.test',now-1000,now]).length,0,'Concurrent mail job cannot claim duplicate');
db.prepare('UPDATE email_deliveries SET lease_until=0').run();db.prepare("UPDATE account_emails SET enabled_at=NULL").run();assert.equal(sql(eligibleEmailSql,[now]).length,0,'One-click unsubscribe immediately prevents delivery');
db.prepare("UPDATE account_emails SET enabled_at=?,verified_at=?").run(now+1,now+1);assert.equal(sql(eligibleEmailSql,[now]).length,0,'Newly verified recipient does not get historical messages');
db.prepare("UPDATE account_emails SET enabled_at=?,verified_at=?").run(now-1000,now-1000);db.prepare("UPDATE user_profiles SET notification_preferences=json_set(notification_preferences,'$.newsletter',json('false'))").run();assert.equal(sql(eligibleEmailSql,[now]).length,0,'Newsletter opt-out is rechecked before delivery');
sql(newsletterSql,[now,'Newsletter','next-week']);assert.equal(db.prepare('SELECT COUNT(*) count FROM notifications').get().count,1,'Opted-out users never generate newsletters');
db.close();console.log('PASS email validation, private HMACs, confirmed provider acceptance/idempotency, real newsletter selection, recipient changes, leases and opt-outs without external sends');
