import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import ts from 'typescript';
import { DatabaseSync } from 'node:sqlite';
import { createRequire } from 'node:module';
import { pathToFileURL } from 'node:url';
const require = createRequire(import.meta.url);
const compile = source => `data:text/javascript;base64,${Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}`;
const protocol = fs.readFileSync('lib/push-protocol.ts','utf8').replace('"web-push"',JSON.stringify(pathToFileURL(require.resolve('web-push')).href));
const { allowedPushEndpoint,parseBrowserSubscription,pushConfiguration,encryptedPushRequest } = await import(compile(protocol));
const { reminderNotificationsSql,organizerNotificationsSql,collectionNotificationsSql,favoriteNotificationsSql,eligiblePushSql,claimPushSql } = await import(compile(fs.readFileSync('lib/notification-queries.ts','utf8')));
for (const value of ['http://fcm.googleapis.com/x','https://localhost/x','https://127.0.0.1/x','https://fcm.googleapis.com.evil.test/x','https://fcm.googleapis.com:444/x','https://a@fcm.googleapis.com/x','https://push.apple.com.evil.test/x','https://example.test/.notify.windows.com']) assert.equal(allowedPushEndpoint(value),false,value);
const key = crypto.createECDH('prime256v1'); key.generateKeys();
const subscription = {endpoint:'https://fcm.googleapis.com/fcm/send/test',keys:{p256dh:key.getPublicKey().toString('base64url'),auth:crypto.randomBytes(16).toString('base64url')}};
assert.deepEqual(parseBrowserSubscription(subscription),subscription);
assert.equal(parseBrowserSubscription({...subscription,keys:{...subscription.keys,p256dh:Buffer.concat([Buffer.from([4]),Buffer.alloc(64)]).toString('base64url')}}),null,'Invalid curve points are rejected');
assert.equal(parseBrowserSubscription({...subscription,keys:{...subscription.keys,auth:'bad'}}),null);
const vapid = require('web-push').generateVAPIDKeys();
const environment = {VAPID_PUBLIC_KEY:vapid.publicKey,VAPID_PRIVATE_KEY:vapid.privateKey,VAPID_SUBJECT:'mailto:operator@example.test'};
const configuration = pushConfiguration(environment);
assert.ok(configuration);
assert.equal(pushConfiguration({...environment,VAPID_PRIVATE_KEY:require('web-push').generateVAPIDKeys().privateKey}),null,'Mismatched VAPID pair fails closed');
assert.equal(pushConfiguration({...environment,VAPID_SUBJECT:'file:///secret'}),null);
const payload = {id:'id',title:'عنوان',message:'متن محرمانه',href:'/notifications'};
const request = encryptedPushRequest(subscription,payload,configuration);
assert.equal(request.init.headers['Content-Encoding'],'aes128gcm');
assert.match(request.init.headers.Authorization,/^vapid /);
assert.equal(request.init.redirect,'error');
assert.ok(!Buffer.from(request.init.body).includes(Buffer.from(payload.message)),'Payload is encrypted');
assert.ok(!Buffer.from(request.init.body).equals(Buffer.from(encryptedPushRequest(subscription,payload,configuration).init.body)),'Independent salt for each encryption');
const db = new DatabaseSync(':memory:'); db.exec('PRAGMA foreign_keys=ON');
for(const {tag} of JSON.parse(fs.readFileSync('drizzle/meta/_journal.json')).entries)db.exec(fs.readFileSync(`drizzle/${tag}.sql`,'utf8'));
const now = Date.now();
const sql = (query,values) => db.prepare(query).all(Object.fromEntries([...new Set(query.match(/\?\d+/g))].map(key=>[key,values[Number(key.slice(1))-1]])));
db.prepare('INSERT INTO users VALUES (?,?,?,?),(?,?,?,?)').run('buyer','09121111111','Buyer',now,'host','09121111112','Host',now);
db.prepare("INSERT INTO sessions VALUES('session','buyer',?)").run(now+86400000);
db.prepare("INSERT INTO user_profiles(user_id,notification_preferences,updated_at) VALUES('buyer',?,?)").run(JSON.stringify({events:true,reminders:true,following:true,collections:true}),now);
db.prepare("INSERT INTO events(id,host_id,title,description,category,venue,address,city,starts_at,ends_at,registration_ends_at,price,created_at) VALUES('event','host','Event','Description','art','Venue','Address','City',?,?,?,0,?)").run(now+3600000,now+7200000,now+300000,now-100);
db.prepare("INSERT INTO reservations(id,user_id,event_id,quantity,total,amount_rial,status,request_key,created_at) VALUES('reservation','buyer','event',1,0,0,'confirmed','reservation',?)").run(now);
db.prepare("INSERT INTO organizer_follows VALUES('buyer','host',?)").run(now-1000);
db.prepare("INSERT INTO collections(id,owner_id,title,published,created_at,updated_at) VALUES('collection','host','Collection',1,?,?)").run(now,now);
db.prepare("INSERT INTO collection_follows VALUES('buyer','collection',?)").run(now-1000);
db.prepare("INSERT INTO collection_events VALUES('collection','event',0,?)").run(now-100);
db.prepare("INSERT INTO push_subscriptions(id,user_id,session_hash,endpoint,p256dh,auth,created_at) VALUES('subscription','buyer','session',?,?,?,?)").run(subscription.endpoint,subscription.keys.p256dh,subscription.keys.auth,now-1000);
const generate = () => [reminderNotificationsSql,organizerNotificationsSql,collectionNotificationsSql].forEach(query=>sql(query,[now,'Notification']));
generate();generate();
assert.equal(db.prepare('SELECT COUNT(*) count FROM notifications').get().count,3,'Generation is idempotent');
assert.equal(sql(eligiblePushSql,[now]).length,3);
db.prepare("UPDATE collections SET published=0").run();assert.equal(sql(eligiblePushSql,[now]).length,2,'Private collection is excluded immediately');
db.prepare("UPDATE collections SET published=1").run();
db.prepare("UPDATE reservations SET status='cancelled'").run();assert.equal(sql(eligiblePushSql,[now]).length,2,'Cancelled reservation no longer receives reminders');
db.prepare("UPDATE reservations SET status='confirmed'").run();
db.prepare("UPDATE user_profiles SET notification_preferences=?").run(JSON.stringify({events:true,reminders:false,following:false,collections:false}));assert.equal(sql(eligiblePushSql,[now]).length,0,'Opt-outs are rechecked at delivery');
db.prepare("UPDATE user_profiles SET notification_preferences=?").run(JSON.stringify({events:true,reminders:true,following:true,collections:true}));
assert.equal(sql(claimPushSql,['reminder:reservation','subscription',now])[0].attempts,1);
assert.equal(sql(claimPushSql,['reminder:reservation','subscription',now]).length,0,'Concurrent job cannot claim same notification');
assert.equal(sql(eligiblePushSql,[now]).length,2);
assert.equal(sql(claimPushSql,['reminder:reservation','subscription',now+60001])[0].attempts,2,'Lease recovers crashed delivery');
db.prepare("UPDATE push_deliveries SET lease_until=0,next_attempt_at=?,attempts=5").run(now+120000);assert.equal(sql(claimPushSql,['reminder:reservation','subscription',now+3600000]).length,0,'Retries are capped');
db.prepare("UPDATE sessions SET expires_at=?").run(now-1);assert.equal(sql(eligiblePushSql,[now]).length,0,'Expired sessions never receive push');
db.prepare("DELETE FROM sessions").run();assert.equal(db.prepare('SELECT COUNT(*) count FROM push_subscriptions').get().count,0,'Logout deletes the session subscription');assert.equal(db.prepare('SELECT COUNT(*) count FROM push_deliveries').get().count,0,'Delivery history cascades with subscription');
db.prepare('DELETE FROM notifications').run();
db.prepare("UPDATE collection_events SET added_at=0").run();db.prepare("UPDATE events SET created_at=0,sample=1").run();generate();assert.equal(db.prepare('SELECT COUNT(*) count FROM notifications').get().count,0,'Historical memberships and sample events do not generate notifications');
db.prepare("UPDATE events SET sample=0").run();
db.prepare("INSERT INTO event_favorites VALUES('buyer','event',?)").run(now);
sql(favoriteNotificationsSql,[now,'Favorite']);
assert.equal(db.prepare("SELECT COUNT(*) count FROM notifications WHERE kind='favorite'").get().count,0,'Favorite alerts require explicit opt-in');
db.prepare("UPDATE user_profiles SET notification_preferences=json_set(notification_preferences,'$.favorites',json('true'))").run();
sql(favoriteNotificationsSql,[now,'Favorite']);sql(favoriteNotificationsSql,[now,'Favorite']);
assert.equal(db.prepare("SELECT COUNT(*) count FROM notifications WHERE kind='favorite'").get().count,1,'Favorite reminders are idempotent');
db.prepare("INSERT INTO sessions VALUES('new-session','buyer',?)").run(now+86400000);
db.prepare("INSERT INTO push_subscriptions(id,user_id,session_hash,endpoint,p256dh,auth,created_at) VALUES('new-subscription','buyer','new-session',?,?,?,?)").run(subscription.endpoint,subscription.keys.p256dh,subscription.keys.auth,now-1000);
assert.equal(sql(eligiblePushSql,[now]).length,1,'Opted-in favorite alerts can be delivered');
db.prepare('DELETE FROM event_favorites').run();assert.equal(sql(eligiblePushSql,[now]).length,0,'Removing a favorite withdraws undelivered alerts');
db.close();
console.log('PASS push endpoint/key validation, real VAPID encryption, idempotent generation, live authorization/preferences, leases, retry cap and session revocation');
