import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {randomBytes,createHash} from 'node:crypto';
import { pathToFileURL } from 'node:url';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const origin=process.env.VISUAL_ORIGIN??'http://127.0.0.1:5190',out=process.env.VISUAL_OUTPUT_PATH??'work/final-qa';
assert.ok(['127.0.0.1','localhost'].includes(new URL(origin).hostname),'Visual tests require a loopback server');
assert.ok(process.env.VISUAL_DATABASE_PATH,'Set VISUAL_DATABASE_PATH to the server’s isolated test database');mkdirSync(out,{recursive:true});
const db=new DatabaseSync(process.env.VISUAL_DATABASE_PATH);db.exec('PRAGMA foreign_keys=ON');const prefix='final-visual-'+randomBytes(4).toString('hex'),host='visual-qa-host',buyer=prefix+'-buyer',empty=prefix+'-empty',eventId=prefix+'-event',now=Math.ceil(Date.now()/300000)*300000;
for(const [id,phone,name] of [[buyer,'099'+String(Math.floor(Math.random()*1e8)).padStart(8,'0'),'نیلوفر احمدی'],[empty,'098'+String(Math.floor(Math.random()*1e8)).padStart(8,'0'),'کاربر آزمون']])db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(id,phone,name,now);
db.prepare('INSERT INTO events(id,host_id,title,description,category,venue,address,city,starts_at,ends_at,registration_ends_at,price,capacity,published,sample,image) VALUES(?,?,?,?,?,?,?,?,?,?,?,0,100,1,0,?)').run(eventId,host,'کارگاه هنر و گفتگو؛ تجربه‌ای تازه در کنار هم','این رویداد فقط برای بررسی محلی رابط کاربری ساخته شده است. برنامه‌ای برای آشنایی با هنر، گفتگو و تجربه‌های تازه.','art','خانهٔ هنر','خیابان ولیعصر، کوچهٔ بهار، پلاک دوازده','تهران',now+172800000,now+180000000,now+86400000,'/images/pottery.jpg');
for(let i=0;i<2;i++)db.prepare('INSERT INTO event_ticket_tiers VALUES(?,?,?,?,0,40,1,?)').run(prefix+'-tier'+i,eventId,i?'بلیت همراه کارگاه':'بلیت عادی','ورود به رویداد و برنامهٔ کارگاه',i);
const createdHost=!db.prepare('SELECT id FROM users WHERE id=?').get(host);
if(createdHost)db.prepare('INSERT INTO users VALUES(?,?,?,?)').run(host,'09900009992','میزبان آزمون بصری',Date.now());
const sessionIds=[];function session(id){const token=randomBytes(32).toString('hex'),hash=createHash('sha256').update(token).digest('hex');sessionIds.push(hash);db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(hash,id,now+3600000);return token;}
const tokens={buyer:session(buyer),host:session(host),empty:session(empty)};
async function api(path,method='GET',data,who='buyer'){const r=await fetch(origin+path,{method,headers:{cookie:'hg_session='+tokens[who],origin,'Content-Type':'application/json'},...(data?{body:JSON.stringify(data)}:{})});assert.ok(r.ok,path+' '+r.status+' '+await r.clone().text());return r.json();}
let collection,series;const browser=await chromium.launch({headless:true,channel:'chrome'}),ctx=await browser.newContext({viewport:{width:375,height:812}}),page=await ctx.newPage(),errors=[],captures=[];page.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url())});page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error'&&!/Failed to load resource: net::ERR_FAILED/.test(e.text()))errors.push(e.text())});await ctx.route(/https:\/\/(?:[a-z]\.)?tile\.openstreetmap\.org\//,route=>route.abort());
page.setDefaultTimeout(15000);
async function identity(who){await ctx.clearCookies();if(who)await ctx.addCookies([{name:'hg_session',value:tokens[who],url:origin}]);}
async function visit(path,selector='h1'){await Promise.all([page.waitForResponse(r=>r.url().endsWith('/api/me')),page.goto(origin+path)]);await page.locator(selector).first().waitFor();await page.waitForFunction(()=>!document.querySelector('[role=status][aria-label="در حال دریافت…"]'));await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));}
async function shot(name,theme){await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));await page.waitForFunction(()=>[...document.images].filter(img=>getComputedStyle(img).display!=='none'&&img.loading!=='lazy').every(img=>img.complete));if(name==='contact'){const box=await page.locator('.el-contact-fields').boundingBox();assert.deepEqual([box.width,box.height],[327,335]);}
if(name==='order'){const box=await page.locator('.el-summary-box').boundingBox();assert.equal(box.height,208);}
await page.screenshot({path:`${out}/${name}-${theme}.png`});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,name+' overflow');captures.push({name,theme,url:new URL(page.url()).pathname});}
try{
 await api('/api/profile','PATCH',{bio:'علاقه‌مند به هنر و تجربه‌های تازه',city:'تهران'});await api('/api/organizers/'+host+'/follow','PUT',{});await api('/api/favorites/'+eventId,'PUT',{});
 collection=(await api('/api/collections','POST',{title:'هنر و تجربه‌های تازه'},'host')).id;await api('/api/collections/'+collection,'PATCH',{title:'هنر و تجربه‌های تازه',description:'مجموعهٔ محلی برای بررسی صفحه و جریان دنبال‌کردن.',published:true,eventIds:[eventId]},'host');
 for(const theme of ['light','dark']){
  await identity('buyer');await page.goto(origin);await page.evaluate(theme=>localStorage.setItem('hg_theme',theme),theme);
  const pages=[['home','/','.el-event-card'],['home-v2','/?layout=v2','.el-event-feature'],['categories','/events','.el-category'],['search','/events?view=all','.el-search'],['filters','/filters','.el-filter-content'],['detail','/events/'+eventId,'.el-detail'],['profile','/account','.el-profile-identity'],['edit-profile','/account/edit','.el-profile-edit'],['following','/following','.el-organizer-row'],['favorites','/favorites','.el-event-list'],['organizer','/organizers/'+host,'.el-organizer-identity'],['collection','/collections/'+collection,'h1'],['settings','/settings','h1'],['notification-settings','/settings/notifications','.el-notification-setting'],['faq','/faq','h1'],['privacy','/privacy','h1'],['about','/about','h1'],['language','/settings/language','h1']];
  for(const [name,path,selector]of pages){console.log(theme,name);await visit(path,selector);await shot(name,theme);}
  await visit('/organizers/'+host,'.el-organizer-identity');for(const [name,label]of [['organizer-collections','مجموعه‌ها'],['organizer-about','درباره']]){await page.getByRole('tab',{name:label,exact:true}).click();await shot(name,theme);}
  await visit('/events/'+eventId+'/tickets','.el-tier-card');await page.getByRole('button',{name:'افزودن بلیت',exact:true}).first().click();await shot('ticket-selection',theme);await page.getByRole('button',{name:'ادامه',exact:true}).click();await page.getByRole('checkbox').check();await shot('contact',theme);await page.getByRole('button',{name:'ادامه',exact:true}).click();await shot('order',theme);await page.getByRole('button',{name:'ادامه',exact:true}).click();await shot('payment',theme);await page.getByRole('button',{name:'تأیید و رزرو',exact:true}).click();await page.getByRole('heading',{name:'بلیتت آماده است!'}).waitFor();await shot('booking-success',theme);
  const booking=db.prepare('SELECT id FROM reservations WHERE user_id=? ORDER BY created_at DESC LIMIT 1').get(buyer).id;
  for(const[name,path,selector]of [['tickets','/reservations','.el-booking-card'],['ticket-detail','/reservations/'+booking,'.el-ticket-paper'],['ticket-qr','/reservations/'+booking+'/qr','.el-qr-code img'],['notifications','/notifications','.el-notification-row']]){await visit(path,selector);await shot(name,theme)}
  await visit('/onboarding','.el-city-card');await shot('city',theme);await page.locator('.el-city-card').first().click();await page.getByRole('heading',{name:'برگزارکننده‌ها را دنبال کن'}).waitFor();await shot('onboarding-follow',theme);await page.getByRole('button',{name:'ادامه',exact:true}).click();await page.getByRole('heading',{name:'به چه چیزهایی علاقه داری؟'}).waitFor();await page.getByRole('button',{name:'موسیقی',exact:true}).click();await shot('interests',theme);
  await identity('empty');await visit('/favorites','.el-empty');await shot('favorites-empty',theme);
  await identity(null);for(const path of ['login','signup','forgot-password']){await visit('/'+path,'.el-auth-heading');await shot(path,theme);if(path!=='forgot-password'){await page.getByLabel('شمارهٔ همراه',{exact:true}).fill('۰۹۱۲۱۲۳۴۵۶۷');await page.getByLabel('رمز عبور',{exact:true}).fill('Only a local visual test');if(path==='signup')await page.getByLabel('نام و نام خانوادگی خریدار',{exact:true}).fill('نیلوفر احمدی');await shot(path+'-filled',theme);}}
  await visit('/welcome','.el-welcome-page');for(let i=0;i<3;i++){await shot('welcome-'+i,theme);if(i<2)await page.getByRole('button',{name:'شروع کنیم',exact:true}).click();}
  for(const width of [320,390,430]){await page.setViewportSize({width,height:812});for(const path of ['/login','/filters','/events?view=all','/settings','/faq']){await visit(path,path.startsWith('/events')?'.el-search':'h1');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,path+' '+width);}}await page.setViewportSize({width:375,height:812});
 }
 await identity('host');await visit('/host/events/'+eventId+'/program','.el-tier-editor');await page.getByLabel('عنوان دورهٔ تازه',{exact:true}).fill('دورهٔ آزمون محلی');await page.getByRole('button',{name:'ساخت دوره',exact:true}).click();await page.waitForFunction(()=>!!document.querySelector('select')?.value);series=await page.locator('select').inputValue();await page.getByRole('button',{name:'افزودن بخش',exact:true}).click();await page.getByLabel('عنوان بخش',{exact:true}).fill('گفتگوی آغازین');await page.getByLabel('اجراکننده',{exact:true}).fill('میزبان آزمون');await page.getByRole('button',{name:'ذخیرهٔ تغییرات',exact:true}).click();await page.getByText('تغییرات ذخیره شد.',{exact:true}).waitFor();const program=(await api('/api/host/events/'+eventId+'/program','GET',undefined,'host')).program;series=program.series_id;assert.equal(program.agenda[0].title,'گفتگوی آغازین');await page.reload();await page.getByLabel('عنوان بخش',{exact:true}).waitFor();assert.equal(await page.getByLabel('عنوان بخش',{exact:true}).inputValue(),'گفتگوی آغازین');await shot('host-program','dark');
 await identity('buyer');db.prepare('UPDATE events SET starts_at=?,ends_at=?,registration_ends_at=? WHERE id=?').run(now-172800000,now-86400000,now-259200000,eventId);
 for(const theme of ['light','dark']){await page.goto(origin);await page.evaluate(t=>localStorage.setItem('hg_theme',t),theme);await visit('/reservations','.el-segmented');await page.getByRole('button',{name:/^گذشته/}).click();await page.locator('.el-booking-past').first().waitFor();await shot('past-tickets',theme);}
 assert.deepEqual(errors,[]);writeFileSync(out+'/manifest.json',JSON.stringify({viewport:{width:375,height:812},adjacentWidths:[320,390,430],captures,errors},null,2));console.log('PASS',captures.length,'captures; genuine booking, community and host program persistence; both themes; responsive and console checks');
}catch(error){await page.screenshot({path:out+"/failure.png"});console.log("BODY",await page.locator("body").innerText());console.log("ERRORS",errors);throw error;}finally{await browser.close();if(collection)db.prepare('DELETE FROM collections WHERE id=?').run(collection);for(const id of sessionIds)db.prepare('DELETE FROM sessions WHERE hash=?').run(id);db.prepare('DELETE FROM reservations WHERE user_id IN (?,?)').run(buyer,empty);db.prepare('DELETE FROM events WHERE id=?').run(eventId);if(series)db.prepare('DELETE FROM event_series WHERE id=?').run(series);db.prepare('DELETE FROM users WHERE id IN (?,?)').run(buyer,empty);if(createdHost)db.prepare('DELETE FROM users WHERE id=?').run(host);db.close();}
