export const copy = {
  checkoutOrganizerUpdates: "این برگزارکننده را دنبال می‌کنم تا از رویدادهای تازه‌اش باخبر شوم.",
  checkoutConsent: "با ادامه، شرایط رزرو و", checkoutBuyerDisclosure: "را می‌پذیرم. نام و شمارهٔ همراه خریدار در فهرست میزبان ثبت می‌شود.", subtotal: "جمع بلیت‌ها", freeBookingMethod: "رزرو رایگان", freeBookingExplanation: "این بلیت رایگان است. پس از تأیید، کد ورود در حساب تو ذخیره می‌شود.",
  facebook: "فیس‌بوک", stories: "استوری", twitter: "توییتر", storyShareHint: "پیوند کپی شد؛ آن را در برنامهٔ دلخواهت به اشتراک بگذار.",
  shareCode: "اشتراک کد", codeCopied: "کد ورود کپی شد.",
  agenda: "برنامهٔ رویداد", manageProgram: "برنامه، ویدیو و تاریخ‌ها", programHint: "بخش‌های برنامه را در بازهٔ زمانی رویداد ثبت کن. هر تاریخِ یک دوره، رویداد مستقل با ظرفیت و بلیت‌های خودش است.",
  programInvalid: "هر بخش به عنوان، نام اجراکننده و زمان معتبر در بازهٔ رویداد نیاز دارد. حداکثر ۲۴ بخش مجاز است.", programMediaInvalid: "پیوند رسانه باید نشانی امن HTTPS و بدون اطلاعات ورود باشد.", programConflict: "برنامه در صفحهٔ دیگری تغییر کرده است. صفحه را دوباره بارگذاری کن.",
  seriesInvalid: "دورهٔ انتخاب‌شده معتبر نیست.", seriesLimit: "حداکثر ۱۰۰ دوره برای هر برگزارکننده مجاز است.", series: "دورهٔ رویداد", noSeries: "رویداد مستقل", newSeries: "عنوان دورهٔ تازه", createSeries: "ساخت دوره", seriesHint: "برای نمایش چند تاریخ در رزرو، رویدادهای خودت را به یک دوره وصل کن.",
  agendaTitle: "عنوان بخش", speaker: "اجراکننده", speakerImage: "پیوند تصویر اجراکننده", addAgenda: "افزودن بخش", removeAgenda: "حذف بخش", startsAt: "آغاز", endsAt: "پایان", videoUrl: "پیوند مستقیم ویدیو", videoHint: "پیوند فایل قابل پخش در مرورگر (مانند MP4)، نه صفحهٔ سرویس ویدیو.", playVideo: "پخش ویدیو", pauseVideo: "توقف ویدیو", videoUnavailable: "ویدیو قابل پخش نیست. دوباره تلاش کن.", videoProgress: "زمان پخش", fullscreen: "تمام‌صفحه", fullscreenUnavailable: "نمای تمام‌صفحه در این مرورگر در دسترس نیست.", muteVideo: "قطع صدا", unmuteVideo: "پخش صدا",

  myFeed: "برای تو",
  fullName: "نام و نام خانوادگی",
  avatarSizeInvalid: "حجم تصویر باید بیشتر از صفر و حداکثر ۵ مگابایت باشد.",
  changeAvatar: "تغییر تصویر پروفایل", removeAvatar: "حذف تصویر", avatarRequired: "یک تصویر JPEG، PNG یا WebP انتخاب کن.", avatarNotFound: "تصویر پروفایل پیدا نشد.", avatarPublicHint: "تصویر پروفایلت در صفحهٔ برگزارکننده و فهرست دنبال‌کننده‌ها دیده می‌شود.", avatarUploading: "در حال بارگذاری تصویر…", profileDetails: "شهر و معرفی", noVerifiedEmail: "ایمیل تأیید نشده است", passwordNotSet: "رمز عبور تنظیم نشده", passwordIsSet: "رمز عبور تنظیم شده است",

  verifiedEmail: "ایمیل تأییدشده", verifyEmail: "تأیید ایمیل", emailVerified: "ایمیل تأیید شد. اکنون می‌توانی اعلان ایمیلی را از تنظیمات فعال کنی.", emailCodeSent: "کد تأیید به این ایمیل فرستاده شد:", emailVerificationCode: "کد تأیید ایمیل", changeEmail: "تغییر ایمیل یا دریافت کد تازه", removeEmail: "حذف ایمیل از حساب", emailRemoved: "ایمیل حذف شد و دریافت ایمیل غیرفعال شد.", unsubscribeEmailHint: "دریافت اعلان‌ها و پیشنهادهای هم‌قدم در ایمیل غیرفعال شود؟",
  emailRequired: "ابتدا ایمیل حسابت را تأیید و اعلان ایمیلی را فعال کن.", emailAlerts: "اعلان در ایمیل", emailAlertsHint: "خبرهای انتخاب‌شده را در ایمیل بگیر", newsletter: "پیشنهادهای هفتگی", newsletterHint: "هر هفته رویدادهای مناسب علاقه‌هایت", newsletterSubject: "پیشنهادهای این هفتهٔ هم‌قدم", unsubscribeEmail: "لغو دریافت ایمیل", emailUnsubscribed: "دریافت ایمیل غیرفعال شد.", emailUnsubscribeInvalid: "این پیوند معتبر نیست. از تنظیمات حساب استفاده کن.",
  emailSettings: "ایمیل حساب", emailInvalid: "نشانی ایمیل معتبر وارد کن.", emailUnconfigured: "ارسال ایمیل هنوز پیکربندی نشده است.", emailDeliveryFailed: "ایمیل ارسال نشد. یک دقیقه دیگر دوباره تلاش کن.", emailVerificationSubject: "کد تأیید ایمیل هم‌قدم", emailVerificationBody: "برای تأیید ایمیل خود در هم‌قدم، این کد را وارد کن:", emailVerificationExpiry: "این کد تا ۱۰ دقیقه معتبر است. اگر این درخواست از طرف تو نیست، این پیام را نادیده بگیر.", emailCodeInvalid: "کد شش‌رقمی ایمیل درست نیست.", emailCodeExpired: "کد منقضی شده یا تعداد تلاش‌ها بیش از حد است. کد تازه بگیر.",

  favoriteAlerts: "رویدادهای پسندیده", favoriteAlertsHint: "پیش از شروع رویدادهای مورد علاقه‌ات باخبر شو", collectionAlerts: "مجموعه‌های دنبال‌شده", collectionAlertsHint: "رویدادهای تازهٔ مجموعه‌های مورد علاقه‌ات", favoriteNotification: "رویداد مورد علاقه‌ات به‌زودی شروع می‌شود",
  notificationSettings: "تنظیمات اعلان", browserPush: "اعلان روی این دستگاه", browserPushHint: "خبرهای تازه را در مرورگر دریافت کن", bookingAlerts: "اعلان بلیت‌ها", bookingAlertsHint: "از صدور بلیت و تأیید رزرو باخبر شو", reminderAlerts: "یادآوری رویدادها", reminderAlertsHint: "یک روز پیش از شروع رویداد رزروشده", followingAlerts: "برگزارکننده‌های دنبال‌شده", followingAlertsHint: "از رویدادهای تازهٔ برگزارکننده‌ها باخبر شو",
  pushUnconfigured: "ارسال اعلان مرورگر هنوز پیکربندی نشده است.", pushUnsupported: "این مرورگر از اعلان پشتیبانی نمی‌کند.", pushDenied: "اعلان در تنظیمات مرورگر مسدود است. برای فعال‌سازی، دسترسی این سایت را تغییر بده.", pushFailed: "تنظیم اعلان ذخیره نشد. دوباره تلاش کن.", pushInvalid: "اطلاعات اشتراک اعلان معتبر نیست.", pushDeviceLimit: "حداکثر پنج دستگاه می‌توانند اعلان دریافت کنند. ابتدا اعلان یکی از دستگاه‌ها را غیرفعال کن.",
  bookingNotification: "بلیت شما صادر شد", reminderNotification: "رویدادت در ۲۴ ساعت آینده شروع می‌شود", organizerNotification: "رویداد تازه از برگزارکنندهٔ دنبال‌شده", collectionNotification: "رویداد تازه در مجموعهٔ دنبال‌شده",

  manageTiers: "مدیریت نوع بلیت", tiersHint: "نام، قیمت و ظرفیت هر نوع بلیت را مشخص کن. تغییرات روی خریدهای قبلی اثر نمی‌گذارد. برای توقف فروش، نوع بلیت را غیرفعال کن.", tierName: "نام نوع بلیت", tierDescription: "توضیح و امکانات", tierPrice: "قیمت به تومان", tierCapacity: "ظرفیت این نوع بلیت", tierUnlimited: "برای ظرفیت نامحدود خالی بگذار", tierActive: "فروش این نوع بلیت فعال است", addTier: "افزودن نوع بلیت", capacityInvalid: "ظرفیت باید عدد صحیح نامنفی باشد.",
  map: "نقشهٔ رویدادها", mapUnavailable: "نقشه دریافت نشد. فهرست رویدادها همچنان در دسترس است.", noMapEvents: "رویدادی با موقعیت ثبت‌شده پیدا نشد", mapEvents: "رویدادهای روی نقشه", mapMarker: "نمایش رویداد روی نقشه", kilometers: "کیلومتر", locationShort: "موقعیت من", chooseCity: "انتخاب شهر",
  browseCategories: "بر اساس موضوع", allResults: "همه", searchResults: "نتایج جستجو", popularSearches: "رویدادهای محبوب", suggestions: "پیشنهاد برای تو", whoToFollow: "چه کسانی را دنبال کنی؟", clearSearch: "پاک کردن جستجو", browseAllEvents: "همهٔ رویدادها", noSearchResults: "نتیجه‌ای پیدا نشد", searchEverything: "رویداد، مجموعه یا برگزارکننده…",
  skip: "فعلاً رد می‌کنم", getStarted: "شروع کنیم", welcomeTitle: "قرارهای خوب را\nهمین‌جا پیدا کن", welcomeDescription: "از موسیقی و هنر تا کتاب و دورهمی؛ رویدادهایی را پیدا کن که با علاقه و حال‌وهوایت جورند.", followWelcomeTitle: "از قرارهای تازهٔ\nدلخواهت باخبر شو", followWelcomeDescription: "برگزارکننده‌های مورد علاقه‌ات را دنبال کن و تجربه‌های تازه را با آدم‌های هم‌سلیقه پیدا کن.", startTitle: "به هم‌قدم خوش آمدی", startDescription: "وارد شو یا حساب بساز؛ قرار بعدی تو همین نزدیکی است.", chooseLocation: "شهرت را انتخاب کن", locationHint: "رویدادهای نزدیکت را پیدا کن. برای شروع، یکی از شهرها را انتخاب کن.", searchCities: "جستجوی شهر…", currentLocation: "استفاده از موقعیت فعلی", availableCities: "شهرهای رویدادها", nearby: "نزدیک من", locationDenied: "دسترسی موقعیت در دسترس نیست. می‌توانی شهر را دستی انتخاب کنی.", followOrganizerTitle: "برگزارکننده‌ها را دنبال کن", followOrganizerHint: "برگزارکننده‌های دلخواهت را انتخاب کن تا پیدا کردن برنامه‌هایشان راحت‌تر شود.", recommendedOrganizers: "برگزارکننده‌های رویدادها", searchOrganizers: "جستجوی برگزارکننده…", chooseInterests: "به چه چیزهایی علاقه داری؟", interestsHint: "موضوع‌های دلخواهت را انتخاب کن تا آن‌ها را در پروفایلت داشته باشی.", searchInterests: "جستجوی علاقه‌مندی…",
  searchHelp: "جستجو در راهنما…", browseTopics: "موضوع‌های راهنما", questionsAbout: "پرسش‌های مربوط به", ticketHelp: "بلیت و رزرو", hostingHelp: "میزبانی", locationHelp: "شهر و موقعیت", featuredQuestions: "پرسش‌های پرتکرار", contactHelp: "پاسخت را پیدا نکردی؟", contactUs: "تماس با ما", whatYouCanDo: "با هم‌قدم چه می‌کنی؟", languageDescription: "زبان فعلی هم‌قدم فارسی است. تاریخ‌ها به تقویم شمسی و قیمت‌ها به تومان نمایش داده می‌شوند.", searchPolicy: "جستجو در حریم خصوصی…",
  previousDates: "روزهای قبل", nextDates: "روزهای بعد", selectDate: "انتخاب تاریخ", dateInput: "تاریخ شمسی", dateExample: "۱۴۰۵/۰۷/۰۸", dateInvalid: "تاریخ شمسی معتبر وارد کن.",
  collectionUnavailable: "این مجموعه برای دنبال کردن در دسترس نیست.", collectionTitle: "نام مجموعه", collectionDescription: "معرفی مجموعه", collectionPublished: "نمایش عمومی مجموعه", collectionDraft: "پیش‌نویس", editCollection: "ویرایش مجموعه", collectionEvents: "رویدادهای مجموعه", collectionSelectHint: "رویدادهای مجموعه را انتخاب کن؛ ترتیب نمایش را با دکمه‌های جابه‌جایی تغییر بده.", moveEarlier: "بالاتر", moveLater: "پایین‌تر", removeEvent: "حذف از مجموعه", deleteCollection: "حذف مجموعه", deleteCollectionConfirm: "این مجموعه و فهرست رویدادهایش حذف شود؟", by: "از", upcomingCount: "رویداد پیش رو", collectionSaved: "مجموعه ذخیره شد.", cancel: "انصراف", delete: "حذف", selected: "انتخاب‌شده", noCollectionEvents: "رویدادی به این مجموعه اضافه نشده است.", cancelBookingConfirm: "رزرو رایگان لغو شود؟ با لغو، کدهای ورود آن دیگر معتبر نخواهند بود.",
  entryCode: "کد ورود", time: "ساعت", showCode: "نمایش کد ورود", viewReceipt: "مشاهده و چاپ رسید", cancelBooking: "لغو رزرو رایگان", checkedIn: "ورود با این بلیت ثبت شده است.", ticketNumber: "بلیت شمارهٔ", scanInstruction: "هنگام ورود، این کد را برای اسکن به میزبان نشان بده.", downloadCode: "دریافت تصویر کد", retryPayment: "ادامهٔ پرداخت", checkPayment: "بررسی وضعیت پرداخت", paymentFollowup: "پرداخت ثبت شده و تأیید رزرو نیاز به پیگیری دارد.",

  password: "رمز عبور", newPassword: "رمز عبور تازه", repeatPassword: "تکرار رمز عبور", showPassword: "نمایش رمز عبور", hidePassword: "پنهان کردن رمز عبور", passwordMismatch: "رمزهای عبور یکسان نیستند.", passwordChanged: "رمزت تغییر کرد!", passwordChangedDescription: "رمز عبور تازه ذخیره شد. می‌توانی به حساب خود برگردی.", resetPassword: "رمز تازه انتخاب کن", verifyCode: "تأیید شمارهٔ همراه", createAccount: "ساخت حساب کاربری", forgotPassword: "رمزت را فراموش کرده‌ای؟", newPasswordHint: "یک رمز عبور تازه برای حسابت انتخاب کن.", codeSent: "کد شش‌رقمی به این شماره ارسال شد:", recoveryHint: "شمارهٔ همراه حساب خود را وارد کن تا کد بازیابی برایت پیامک شود.", signupHint: "همراه ما، تجربه‌های تازه را پیدا کن.", loginHint: "وارد شو و رویدادهای دلخواهت را پیدا کن.", verify: "تأیید کد", resend: "ارسال دوبارهٔ کد", passwordHint: "از ۱۲ تا ۱۲۸ نویسه برای رمز عبور استفاده کن.", signIn: "ورود", signUp: "ثبت‌نام", sendCode: "دریافت کد تأیید", passwordLogin: "ورود با رمز عبور", smsLogin: "ورود با کد پیامکی", signupTerms: "با ثبت‌نام، شرایط استفاده و حریم خصوصی هم‌قدم را می‌پذیرم.", noAccount: "هنوز حساب نداری؟", haveAccount: "قبلاً ثبت‌نام کرده‌ای؟",

  welcomeBack: "خوش برگشتی!", accountRequired: "برای ادامه وارد حساب هم‌قدم خود شو.", noContent: "هنوز چیزی اینجا نیست", events: "رویدادها", collections: "مجموعه‌ها", aboutProfile: "درباره", profileSections: "بخش‌های پروفایل", following: "دنبال‌شده‌ها", followers: "دنبال‌کننده", follow: "دنبال کردن", organizers: "برگزارکننده‌ها", discoverOrganizers: "کشف برگزارکننده‌ها", noFollowing: "هنوز کسی را دنبال نکرده‌ای", noBiography: "معرفی ثبت نشده است.", biography: "دربارهٔ من", saveChanges: "ذخیرهٔ تغییرات", changesSaved: "تغییرات ذخیره شد.", newCollection: "مجموعهٔ تازه", createCollection: "ساخت مجموعه", hostDashboard: "مدیریت رویدادها", adminDashboard: "مدیریت هم‌قدم", markAllRead: "همه را خواندم", noNotifications: "اعلان تازه‌ای نداری",

  saveFailed: "ذخیره نشد. فضای ذخیره‌سازی مرورگر را بررسی کنید.",
  notFound: "رویداد پیدا نشد.", spotsLeft: "جای خالی", shareEvent: "این رویداد را به اشتراک بگذار", copyLink: "کپی پیوند", email: "ایمیل", ticketBenefits: "جزئیات بلیت", selectedTickets: "بلیت انتخاب‌شده", contactInformation: "اطلاعات خریدار", orderSummary: "خلاصهٔ سفارش", paymentMethod: "روش پرداخت", payment: "پرداخت", payOnline: "پرداخت آنلاین", zarinpal: "درگاه امن زرین‌پال", payExplanation: "جای شما برای ۱۵ دقیقه نگه داشته می‌شود. پرداخت در صفحهٔ امن زرین‌پال انجام می‌شود.", contactHint: "همهٔ بلیت‌ها با این نام ثبت می‌شوند. هر نفر کد ورود جداگانه دارد.", acceptTerms: "شرایط رزرو و حریم خصوصی را می‌پذیرم.", bookingSuccess: "بلیتت آماده است!", bookingSuccessDescription: "جزئیات رویداد و بلیت‌ها در حساب تو ذخیره شد.", viewTickets: "مشاهدهٔ بلیت‌ها", backHome: "بازگشت به خانه", bookingPending: "رزرو در انتظار پرداخت است.", bookingBusy: "در حال ثبت رزرو…", demoPayment: "حالت آزمایشی: این رزرو بدون دریافت وجه تأیید می‌شود.", edit: "ویرایش", purchaseTerms: "شرایط رزرو", fees: "کارمزد", checkoutDate: "تاریخ رویداد",

  app: "هم‌قدم", tagline: "یک قرار خوب، همین نزدیکی.", near: "قرار بعدی در", allCities: "همهٔ شهرها", iran: "ایران",
  home: "خانه", explore: "کشف", favorites: "علاقه‌ها", tickets: "بلیت‌ها", profile: "پروفایل", navigation: "منوی اصلی",
  search: "جستجوی رویدادها…", searchLabel: "جستجوی رویداد", upcoming: "رویدادهای پیش رو", popular: "محبوب‌ترین‌ها", all: "مشاهده همه", join: "شرکت", free: "رایگان", toman: "تومان",
  back: "بازگشت", close: "بستن", filters: "فیلترها", dates: "زمان", categories: "دسته‌بندی‌ها", price: "قیمت", anyPrice: "همهٔ قیمت‌ها", freeOnly: "فقط رایگان", apply: "اعمال", allDays: "همهٔ روزها", today: "۲۴ ساعت آینده", week: "۷ روز آینده", city: "شهر", reset: "پاک کردن فیلترها",
  loading: "در حال دریافت…", retry: "تلاش دوباره", empty: "رویدادی پیدا نشد", emptyDescription: "زمان یا دسته‌بندی را تغییر دهید.", favoriteEmpty: "هنوز علاقه‌مندی نداری", favoriteDescription: "رویدادهای دلخواهت را ذخیره کن تا بعداً راحت پیدایشان کنی.", findEvents: "کشف رویدادها",
  aboutEvent: "دربارهٔ رویداد", more: "بیشتر بخوان", less: "نمایش کمتر", getTicket: "رزرو بلیت", share: "اشتراک‌گذاری", saved: "از علاقه‌ها برداشتن", save: "ذخیره در علاقه‌ها", calendar: "افزودن به تقویم", venue: "محل برگزاری", viewLocation: "مشاهدهٔ نشانی", until: "تا", remaining: "ظرفیت باقی‌مانده", unlimited: "ظرفیت نامحدود", soldOut: "ظرفیت تکمیل", closed: "ثبت‌نام پایان یافته", sample: "این رویداد نمونه است و برنامهٔ واقعی این مکان نیست.", paymentUnavailable: "پرداخت این رویداد در دسترس نیست.", copied: "پیوند کپی شد", shareError: "اشتراک‌گذاری انجام نشد.",
  chooseTicket: "انتخاب بلیت", regular: "بلیت عادی", quantity: "تعداد بلیت", increase: "افزودن بلیت", decrease: "کم کردن بلیت", continue: "ادامه", details: "جزئیات رزرو", buyer: "نام و نام خانوادگی خریدار", phone: "شمارهٔ همراه", total: "مبلغ کل", confirm: "تأیید و رزرو", login: "ورود / ثبت‌نام", loginRequired: "برای دیدن بلیت‌ها وارد شوید.", noTickets: "هنوز بلیتی نداری", past: "گذشته", upcomingTickets: "پیش رو", confirmed: "تأییدشده", pending: "در انتظار تأیید", cancelled: "لغوشده", expired: "منقضی‌شده", download: "دریافت بلیت", ticketDetail: "جزئیات بلیت", bookingReference: "شمارهٔ رزرو",
  settings: "تنظیمات", general: "تنظیمات عمومی", accountSettings: "حساب کاربری", other: "سایر", language: "زبان", persian: "فارسی", darkMode: "حالت تاریک", editProfile: "ویرایش پروفایل", faq: "پرسش‌های متداول", about: "دربارهٔ هم‌قدم", privacy: "حریم خصوصی", logout: "خروج از حساب", notifications: "اعلان‌ها", nameInvalid: "نام و نام خانوادگی را بین ۲ تا ۸۰ نویسه وارد کنید.",
} as const;

export const categoryCopy = [
  { id: "all", label: "همهٔ رویدادها" }, { id: "music", label: "موسیقی" },
  { id: "art", label: "هنر و تجربه" }, { id: "books", label: "کتاب و گفتگو" },
  { id: "games", label: "بازی و دورهمی" }, { id: "coffee", label: "قهوه و کافه" },
] as const;

export const faqTopicPatterns = { tickets: /بلیت|رزرو|پرداخت/, hosting: /میزبان|منتشر/, location: /موقعیت|شهر/ };
export function categoryLines(label: string) { return label.replace(" و ", "\nو "); }
